- name: install Redis repo file as a rpm
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: module enabling redis:remi-6.2 -y
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: installing redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: replace from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: enable and starting redis
  ansible.builtin.import_role:
    name: common
    tasks_from: enable-start

