- name: check app Directory exists or not
  ansible.builtin.stat:
    path: /app
  register: Directory
  ignore_errors: yes

- name: print the output of Directory
  ansible.builtin.debug:
    msg: "output: {{Directory}}"

- name: create a app Directory if not found
  ansible.builtin.file:
    path: /app
    state: directory
  when: Directory.stat.exists == False