- name: check user exists or not
  ansible.builtin.shell: id roboshop
  register: user
  ignore_errors: yes

- name: print user outpul
  ansible.builtin.debug:
    msg: "Output: {{user}}"

- name: create user roboshop if no user
  ansible.builtin.user:
    name: roboshop
  when: user.rc != 0


